type: environment
definition: tbd.yml
config:
  name: azureml/curated/tensorflow-2.7-ubuntu20.04-py38-cuda11-gpu
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    pin_version_files:
    - Dockerfile