image:
  name: "nvcr.io/nvidia/tritonserver:22.03-py3"
  os: linux
environment:
  metadata:
    MachineLearningFramework: {}
    Purpose:
      HasTrainingSupport: false
      HasInferencingSupport: true
