image:
  name: azureml/curated/tensorflow-2.9-ubuntu20.04-py38-cuda11-gpu
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
  publish:
    location: mcr
    visibility: public
environment:
  metadata:
    Cuda:
      CudaVersion: "11.3"
      CuDnnVersion: "8.2.0"
      NcclVersion: "2.9.9"
    MachineLearningFramework:
      name: TensorFlow
      version: "2.9"
    Mpi:
      name: OpenMpi
      version: "4.1.0"
    Purpose:
      HasTrainingSupport: true
      HasInferencingSupport: false
    Runtime:
      name: Python
      version: "3.8"
    Os:
      name: Ubuntu
      version: "20.04"
