image:
  name: azureml/curated/mlflow-py312-inference
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - conda_dependencies.yaml
  publish:
    location: mcr
    visibility: public
