image:
  name: azureml/curated/designer-pytorch-train
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
      - Dockerfile
      - conda_dependencies.yaml
  publish:
    location: mcr
    visibility: public
