image:
  name: azureml/curated/docker-tools
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
  publish:
    location: mcr
    visibility: public
  tags:
    System: ""
    Docker: ""
    Oras: "1.2.0"
    Trivy: "0.69.1"
