image:
  name: mcr.microsoft.com/azureml/curated/acft-hf-nlp-gpu
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - requirements.txt
  publish:
    location: mcr
    visibility: unlisted
