image:
  name: azureml/curated/acpt-pytorch-2.7-cuda12.6
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - requirements.txt
  publish:
    location: mcr
    visibility: public
