image:
  name: azureml/curated/azureml-tensorflow-2.6-ubuntu20.04-py38-cuda11-gpu
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - conda_dependencies.yaml
  publish:
    location: mcr
    visibility: public
environment:
  metadata:
    Cuda:
      CudaVersion: "11.1.1"
      CuDnnVersion: "8.0.5.39"
      NcclVersion: "2.8.4"
    MachineLearningFramework:
      name: TensorFlow
      version: "2.6"
    Mpi:
      name: OpenMpi
      version: "4.1.0"
    Purpose:
      HasTrainingSupport: true
      HasInferencingSupport: false
    Runtime:
      name: Python
      version: "3.8"
    Os:
      name: Ubuntu
      version: "20.04"
