image:
  name: azureml/curated/model-evaluation
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - conda.yaml
  publish:
    location: mcr
    visibility: public