type: environment
definition_file: tbd.yml
config:
  image_name: azureml/curated/tensorflow-2.8-ubuntu20.04-py38-cuda11-gpu
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
    - conda_dependencies.yml