name: Get changed files under given directory

on:
  workflow_call:
    inputs:
      folder_path:
        type: string
        default: "**"
      forked_pr_input:
        type: string
        default: ''
    outputs:
      files-changed:
        description: List of changed files under given directory
        value: ${{ jobs.check-directory-file-changes.outputs.files-changed }}
      files-added:
        description: List of added files under given directory
        value: ${{ jobs.check-directory-file-changes.outputs.added-files }}

defaults:
  run:
    shell: bash

jobs:
  check-directory-file-changes:
    name: Get changed files under given directory
    runs-on: ubuntu-latest 

    permissions:
      # Required to clone repo
      contents: read

    steps:
      - name: Clone branch
        uses: Azure/azureml-assets/.github/actions/clone-repo@main
        with:
          forked-pr: ${{ inputs.forked_pr_input }}
          fetch-depth: 2

      - name: Get changed files under directory
        id: changed-scripts
        uses: tj-actions/changed-files@v46
        with:
          files: ${{ inputs.folder_path }}
          files_separator: ','
          separator: ','
          sha: ${{ env.merge_commit_hash || github.sha }}

      - name: Check if changes were made to directory
        id: check-changed-files
        run : |
          if ${{ steps.changed-scripts.outputs.all_changed_and_modified_files == '' }}; then
            echo "No changed files under ${{ inputs.folder_path }}"
          else
            echo "Updated file(s) found under ${{ inputs.folder_path }}: ${{ steps.changed-scripts.outputs.all_changed_and_modified_files }}"
          fi

          if ${{ steps.changed-scripts.outputs.added_files == '' }}; then
            echo "No added files under ${{ inputs.folder_path }}"
          else
            echo "Added file(s) found under ${{ inputs.folder_path }}: ${{ steps.changed-scripts.outputs.added_files }}"
          fi

          echo "files-changed=${{ steps.changed-scripts.outputs.all_changed_and_modified_files }}" >> "$GITHUB_OUTPUT"
          echo "files-added=${{ steps.changed-scripts.outputs.added_files }}" >> "$GITHUB_OUTPUT"

          cat "$GITHUB_OUTPUT"
    outputs:
      files-changed: ${{ steps.check-changed-files.outputs.files-changed }}
      files-added: ${{ steps.check-changed-files.outputs.files-added }}