name: close-stale-items

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Close Stale Items
      uses: actions/stale@v9.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 60
        days-before-issue-close: 7
        days-before-pr-stale: 30
        days-before-pr-close: 7
        stale-issue-message: 'This issue has been marked as stale because it has been inactive for 60 days.'
        close-issue-message: 'This issue has been automatically closed due to inactivity.'
        stale-pr-message: 'This pull request has been marked as stale because it has been inactive for 30 days.'
        close-pr-message: 'This pull request has been automatically closed due to inactivity.'
        debug-only: true
