name: environments-ci

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - .github/**
    types:
      - opened
      - labeled
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      asset_dirs:
        description: Asset directories
        default: .,!test,!scripts
        required: true

defaults:
  run:
    shell: bash

jobs:
  check-execution-context:
    name: Check execution context
    runs-on: ubuntu-latest

    permissions:
      # Required to clone repo
      contents: read

    steps:
      - name: Check execution context
        uses: Azure/azureml-assets/.github/actions/check-execution-context@main
      
    outputs:
      continue: ${{ env.continue }}
      trusted_ref: ${{ env.trusted_ref }}
      testing_ref: ${{ env.testing_ref }}

  build-images:
    name: Build and test images
    if: fromJSON(needs.check-execution-context.outputs.continue)
    runs-on: ubuntu-latest
    needs: check-execution-context
    environment: Testing

    permissions:
      # Required to clone repo
      contents: read
      # Required for OIDC login to Azure
      id-token: write

    env:
      default_asset_dirs: .,!test,!scripts
      scripts_azureml_assets_dir: scripts/azureml-assets
      scripts_environment_dir: scripts/azureml-assets/azureml/assets/environment
      scripts_setup_dir: scripts/setup
      asset_config_filename: asset.yaml
      build_logs_artifact_name: build-logs
      built_dir: built-environments
      trusted_dir: trusted
      testing_dir: testing
      trusted_ref: ${{ needs.check-execution-context.outputs.trusted_ref }}
      testing_ref: ${{ needs.check-execution-context.outputs.testing_ref }}

    steps:
      - name: Collapse branches
        if: env.testing_ref == null
        run: echo "testing_dir=$trusted_dir" >> $GITHUB_ENV

      - name: Clone trusted branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.trusted_ref }}
          fetch-depth: 0
          path: ${{ env.trusted_dir }}
      
      - name: Clone testing branch
        if: env.testing_ref != null
        uses: actions/checkout@v3
        with:
          ref: ${{ env.testing_ref }}
          fetch-depth: 2
          path: ${{ env.testing_dir }}
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24
        with:
          path: ${{ env.testing_dir }}
          files_separator: ','
          separator: ','
      
      - name: Use Python 3.8 or newer
        uses: actions/setup-python@v3
        with:
          python-version: '>=3.8'
    
      - name: Install dependencies
        run: pip install -e $trusted_dir/$scripts_azureml_assets_dir
      
      - name: Log in to Azure and create resources
        uses: Azure/azureml-assets/.github/actions/create-azure-resources@main
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scripts-setup-dir: ${{ env.trusted_dir }}/${{ env.scripts_setup_dir }}

      - name: Build and test changed images
        id: build-changed-images
        run: python -u $GITHUB_WORKSPACE/$trusted_dir/$scripts_environment_dir/build.py -i "${{ github.event.inputs.asset_dirs || env.default_asset_dirs }}" -a $asset_config_filename -o '${{ runner.temp }}'/$built_dir -l '${{ runner.temp }}'/$build_logs_artifact_name -P -g $resource_group -r $container_registry -T 'python -V' -c "${{ steps.changed-files.outputs.all_modified_files }}"
        working-directory: ${{ env.testing_dir }}

      - name: Upload build logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.build_logs_artifact_name }}
          path: ${{ runner.temp }}/${{ env.build_logs_artifact_name }}
